name: update

on:
  push:
      branches: master
  schedule:
    - cron: "30 12 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends curl rpm2cpio cpio python3 python3-requests
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - run: |
        python3 update.py
    - run: |
        git branch -D master
        git push --all https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push --tags https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
